- project:
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
      - openstack-python3-ussuri-jobs-neutron
      - openstack-lower-constraints-jobs-neutron
    check:
      jobs:
        - openstack-tox-cover:
            required-projects:
              - openstack/neutron
            voting: false
        - ovn-octavia-provider-functional
    gate:
      jobs:
        - ovn-octavia-provider-functional
